export const RECEIVED_CATEGORIES = "RECEIVED_CATEGORIES"
export const RECEIVED_COMMENTS = "RECEIVED_COMMENTS"
export const RECEIVED_POSTS = "RECEIVED_POSTS"

export const RECEIVED_NEW_COMMENT = "RECEIVED_NEW_COMMENT"

export const RECEIVED_DELETED_POST = "RECEIVED_DELETED_POST"

export const RECEIVED_NEW_POST = "RECEIVED_NEW_POST"

export const RECEIVED_DELETED_COMMENT = "RECEIVED_DELETED_COMMENT"

export const RECEIVED_UPDATED_POST = "RECEIVED_UPDATED_POST"
export const RECEIVED_UPDATED_COMMENT = "RECEIVED_UPDATED_COMMENT"
export const RECEIVED_UPDATED_POST_SCORE = "RECEIVED_UPDATED_POST_SCORE"